/* Generated by tools/symdump.py -- original prototypes from PSX.SYM. */

void InitGraphicsSystem(void);  /* 3DCTRL.C:45 */
void InitLighting(int fogflag);  /* 3DCTRL.C:79 */
void SetupLighting(short id, short r, short g, short b, int deg1, int deg2);  /* 3DCTRL.C:97 */
void StartDrawing(void);  /* 3DCTRL.C:140 */
void EndDrawing(short sync);  /* 3DCTRL.C:151 */
void UpdateCoordinate(struct ModelType *dim);  /* 3DCTRL.C:203 */
void UpdateCoordinate2(struct ModelType *dim);  /* 3DCTRL.C:212 */
struct VECTOR * GetAbsolutePosition(struct ModelType *model, short x, short y, short z);  /* 3DCTRL.C:221 */
long DrawClip(struct ModelType *objp, long *xy);  /* 3DCTRL.C:240 */
struct ModelType * LoadModel(unsigned long *adr);  /* 3DCTRL.C:269 */
short DrawModel(struct ModelType *objp);  /* 3DCTRL.C:297 */
void DisposeModel(struct ModelType *objp);  /* 3DCTRL.C:312 */
struct ModelType * CreateCloneModel(struct ModelType *objp);  /* 3DCTRL.C:319 */
struct ModelArchiveType * LoadModelArchive(unsigned long *adr, struct ModelType *prnt);  /* 3DCTRL.C:335 */
short DrawModelArchive(struct ModelArchiveType *mad, long gap);  /* 3DCTRL.C:393 */
void DisposeModelArchive(struct ModelArchiveType *mad);  /* 3DCTRL.C:425 */
struct ModelArchiveType * CreateCloneModelArchive(struct ModelArchiveType *mad);  /* 3DCTRL.C:438 */
struct OrnamentType * LoadOrnament(unsigned long *adr);  /* 3DCTRL.C:471 */
short DrawOrnament(struct OrnamentType *objp);  /* 3DCTRL.C:496 */
void DisposeOrnament(struct OrnamentType *objp);  /* 3DCTRL.C:510 */
struct OrnamentType * CreateCloneOrnament(struct OrnamentType *objp);  /* 3DCTRL.C:518 */
void UpdateOrnament(struct OrnamentType *objp, short ry);  /* 3DCTRL.C:532 */
struct Sprite3D * SetupSprite(struct Sprite3D *orgsprt, struct GsIMAGE *image);  /* 3DCTRL.C:546 */
short DrawSprite(struct Sprite3D *sprt);  /* 3DCTRL.C:593 */
void DisposeSprite(struct Sprite3D *sprt);  /* 3DCTRL.C:611 */
struct BackGround * SetupBG(struct GsIMAGE *image, short w, short h);  /* 3DCTRL.C:622 */
short DrawBG(struct BackGround *bg);  /* 3DCTRL.C:686 */
void DisposeBG(struct BackGround *bg);  /* 3DCTRL.C:697 */
void ViewAdjustBG(struct BackGround *bg);  /* 3DCTRL.C:708 */
short LoadTIM(unsigned long *adr);  /* 3DCTRL.C:718 */
short GetTIMInfo(unsigned long *adr, struct GsIMAGE *image);  /* 3DCTRL.C:749 */
short LoadTIMpack(unsigned long *adr);  /* 3DCTRL.C:759 */
short GetTIMpackInfo(unsigned long *adr, struct GsIMAGE *image, int idx);  /* 3DCTRL.C:802 */
struct MotionPackType * LoadMotion(unsigned long *data);  /* ACTION.C:77 */
struct MotionDataType * SearchMotion(short id);  /* ACTION.C:100 */
struct MotionRegistType * SetupMotionRegist(struct MotionRegistType *mrp);  /* ACTION.C:126 */
struct MotionManager * SetupMotionManager(struct ModelArchiveType *mad, struct MotionRegistType *mot);  /* ACTION.C:139 */
void DisposeMotionManager(struct MotionManager *mmp);  /* ACTION.C:160 */
short GetMotionID(struct MotionManager *mmp, short mid);  /* ACTION.C:169 */
short UpdateMotion(struct MotionManager *mmp, short mid);  /* ACTION.C:182 */
short PlayMotion(struct MotionManager *mmp, short mode);  /* ACTION.C:220 */
short HoldMotion(struct MotionManager *mmp);  /* ACTION.C:242 */
short SweepMotion(struct MotionManager *mmp);  /* ACTION.C:272 */
short ActiveMotion(struct MotionManager *mmp);  /* ACTION.C:307 */
void SetupSpline(struct MotionManager *mmp);  /* ACTION.C:344 */
void UpdateSplineControl(struct SplineControlType *spc);  /* ACTION.C:365 */
void GetSpline(struct SVECTOR *vect, struct SplineControlType *spc, short cnt);  /* ACTION.C:388 */
void SetupAppearance(short mode, short stage);  /* APPEAR.C:109 */
struct Humanoid * SetupCharacterParameter(short type, struct Humanoid *human);  /* APPEAR.C:173 */
struct Humanoid * BreedLife(short type, long x, long y, long z, long r);  /* APPEAR.C:202 */
short GetAttackDBID(struct Humanoid *human, short mid);  /* APPEAR.C:258 */
void GetWeaponData(struct Humanoid *human, short body, short wid, short wpid, int wep);  /* APPEAR.C:270 */
void SetupWeapon(struct Humanoid *human);  /* APPEAR.C:299 */
void DisposeWeapon(struct Humanoid *human);  /* APPEAR.C:364 */
void EquipWeapon(struct Humanoid *human, short mode);  /* APPEAR.C:380 */
void InitSoundEffect(void);  /* AUDIO.C:28 */
struct SoundEffect * SetupSE(unsigned char *vab);  /* AUDIO.C:40 */
void DisposeSE(struct SoundEffect *se);  /* AUDIO.C:61 */
short PlaySE(struct SoundEffect *se, short pt, long dv);  /* AUDIO.C:72 */
void StopSE(short voice);  /* AUDIO.C:94 */
void SetCameraMode(enum TCameraMode mode);  /* CAMERA.C:85 */
void QuakeCamera(int i);  /* CAMERA.C:99 */
void SnapCameraTargetVector(void);  /* CAMERA.C:106 */
static void MakeDifSub(struct VECTOR *src, struct VECTOR *target, struct VECTOR *dest, struct TMakeDifInfo *info);  /* CAMERA.C:377 */
void MakeDif(struct GsRVIEW2 *vinfo, struct GsRVIEW2 *target, struct GsRVIEW2 *vdif);  /* CAMERA.C:418 */
void AntiWall(struct GsRVIEW2 *vinfo, struct GsRVIEW2 *target);  /* CAMERA.C:432 */
static void MakeCameraPosition(struct VECTOR *orgpos, struct SVECTOR *orgrot, struct SVECTOR *campos, struct SVECTOR *ref, struct GsRVIEW2 *vDif);  /* CAMERA.C:533 */
void CameraType1(struct Humanoid *pl, struct GsRVIEW2 *vDif);  /* CAMERA.C:603 */
void Camera(void);  /* CAMERA.C:784 */
void CameraDirection(struct Humanoid *pl, struct GsRVIEW2 *vDif);  /* CAMERA.C:898 */
void CVAsetup(void);  /* CHRANIM.C:64 */
short CVAsequence(short sid);  /* CHRANIM.C:83 */
short CVAupdate(void);  /* CHRANIM.C:145 */
short CVArun(void);  /* CHRANIM.C:238 */
void AVCameraSetup(void);  /* CHRANIM.C:289 */
void AVCameraControl(void);  /* CHRANIM.C:322 */
void SetupTelop(unsigned char *telop);  /* CHRANIM.C:372 */
void DrawTelop(void);  /* CHRANIM.C:420 */
unsigned long * LoadAreaMap(unsigned long *adr);  /* CONFLICT.C:47 */
void DisposeAreaMap(unsigned long *area);  /* CONFLICT.C:74 */
long ComputeAreaLevel(struct AreaNodeType *node, long x, long z);  /* CONFLICT.C:83 */
long GetAreaMapLevel(unsigned long *area, long x, long y, long z, int mode);  /* CONFLICT.C:107 */
long GetAreaMapVector(unsigned long *area, struct MapVector *mvp, struct VECTOR *pos, long wide, int mode);  /* CONFLICT.C:180 */
struct VECTOR * GetAreaMapPassage(unsigned long *area, struct VECTOR *pos, struct SVECTOR *vect, short n);  /* CONFLICT.C:223 */
void InitConflict(void);  /* CONFLICT.C:260 */
short InsertConflict(struct ModelType *model);  /* CONFLICT.C:283 */
void DeleteConflict(struct ModelType *model);  /* CONFLICT.C:310 */
void ComputeAllConflict(void);  /* CONFLICT.C:329 */
short GetConflictResult(struct ModelType *model, short index);  /* CONFLICT.C:382 */
void DrawSpriteXYZ(struct GsSPRITE *sprt, long x, long y, long z, long scale);  /* EFFECT.C:204 */
long CGetLevel(struct AreaNodeType **hint, long x, long y, long z, unsigned long flag);  /* EFFECT.C:220 */
void InitEffect(void);  /* EFFECT.C:271 */
void DrawEffect(void);  /* EFFECT.C:366 */
void DrawTargetS(long x, long y, long z, long color);  /* EFFECT.C:442 */
void RotateVector(struct VECTOR *vec, int rx, int ry, int rz);  /* EFFECT.C:470 */
void RotateVectorS(struct SVECTOR *vec, int rx, int ry, int rz);  /* EFFECT.C:480 */
long GetVectorLength(long dx, long dy, long dz);  /* EFFECT.C:493 */
int GetVectorDistance(struct VECTOR *v1, struct VECTOR *v2);  /* EFFECT.C:509 */
void GetVectorRotation(struct VECTOR *start, struct VECTOR *end, int *rx, int *ry);  /* EFFECT.C:532 */
void GetScreenPosition(long x, long y, long z, struct SVECTOR *scr);  /* EFFECT.C:543 */
void PrepareGetScreenPositionS(void);  /* EFFECT.C:577 */
void GetScreenPositionS(long x, long y, long z, struct SVECTOR *scr);  /* EFFECT.C:588 */
void DrawTarget(long x, long y, long z, long color);  /* EFFECT.C:602 */
void SetPadState(short pad, short index);  /* EFFECT.C:614 */
void DrawBlood(struct tag_EffectSlot *ef);  /* EFFECT.C:657 */
void SetBlood(struct VECTOR *pos, struct SVECTOR *vect, short n, short time);  /* EFFECT.C:745 */
static void DrawSmoke(struct tag_EffectSlot *ef);  /* EFFECT.C:794 */
void SetSmoke(struct VECTOR *pos, struct SVECTOR *vect, short n, short time);  /* EFFECT.C:835 */
void SetSmokeS(struct VECTOR *pos, short vx, short vy, short vz, int time);  /* EFFECT.C:858 */
static void DrawImpact(struct tag_EffectSlot *ef);  /* EFFECT.C:876 */
void SetImpact(struct VECTOR *pos, short size, short type);  /* EFFECT.C:893 */
static void DrawBleed(struct tag_EffectSlot *ef);  /* EFFECT.C:910 */
void SetBleed(struct VECTOR *pos, struct SVECTOR *vec, int time, long col);  /* EFFECT.C:946 */
void SetBleeds(struct VECTOR *pos, short grange, short srange, short n, int time, long col);  /* EFFECT.C:963 */
static void DrawSplash(struct tag_EffectSlot *ef);  /* EFFECT.C:978 */
void SetSplash(struct VECTOR *pos, short sx, short sy, int speed);  /* EFFECT.C:1023 */
static void DrawFrame(struct tag_EffectSlot *ef);  /* EFFECT.C:1044 */
void SetFrame(struct VECTOR *pos, short size, short time, struct _GsCOORDINATE2 *super);  /* EFFECT.C:1095 */
void SetBleedsDir(struct VECTOR *pos, struct SVECTOR *vec, short grange, short n, int time, long col);  /* EFFECT.C:1115 */
static void DrawGore(struct tag_EffectSlot *ef);  /* EFFECT.C:1131 */
void SetGore(struct VECTOR *pos, struct SVECTOR *vec, int time, long col);  /* EFFECT.C:1161 */
static void DrawExplosion(struct tag_EffectSlot *ef);  /* EFFECT.C:1177 */
void SetExplosion(struct VECTOR *pos, struct SVECTOR *vect);  /* EFFECT.C:1236 */
static void DrawHinoko(struct tag_EffectSlot *ef);  /* EFFECT.C:1258 */
void SetHinoko(struct VECTOR *pos, struct SVECTOR *power, int n);  /* EFFECT.C:1321 */
static void DrawFlyWire(struct tag_EffectSlot *ef);  /* EFFECT.C:1346 */
int SetFlyWire(struct VECTOR *start, struct VECTOR *end);  /* EFFECT.C:1384 */
void SetWire(struct VECTOR *start, struct VECTOR *end, struct VECTOR *center, long len);  /* EFFECT.C:1428 */
static void SetLightningI(struct VECTOR *start, struct VECTOR *end, int gen, short r, int g, int b);  /* EFFECT.C:1500 */
void SetLightning(struct VECTOR *start, struct VECTOR *end, short r, short g, int b);  /* EFFECT.C:1562 */
void DrawShadow(struct Humanoid *human);  /* EFFECT.C:1572 */
struct AfterimageType * SetupAfterimage(struct ModelType *model, short len);  /* EFFECT.C:1667 */
void DisposeAfterimage(struct AfterimageType *afi);  /* EFFECT.C:1706 */
short DrawAfterimage(struct AfterimageType *afi, short disp);  /* EFFECT.C:1717 */
void SetPolyXF4(struct POLY_XF4 *ply, short attrib);  /* EFFECT.C:1770 */
void AddXF4(void *ot, struct POLY_XF4 *ply);  /* EFFECT.C:1780 */
void DrawXF4(struct POLY_XF4 *ply);  /* EFFECT.C:1785 */
void SetPolyXG4(struct POLY_XG4 *ply, short attrib);  /* EFFECT.C:1793 */
void AddXG4(void *ot, struct POLY_XG4 *ply);  /* EFFECT.C:1803 */
void DrawXG4(struct POLY_XG4 *ply);  /* EFFECT.C:1808 */
void FadeOutDirect(short time, short attrib, unsigned char r, unsigned char g, int b);  /* EFFECT.C:1816 */
struct TexScroll * SetupTexScroll(struct GsIMAGE *img, short x, short y, short mode);  /* EFFECT.C:1853 */
void UpdateTexScroll(struct TexScroll *tscr);  /* EFFECT.C:1884 */
void InitFileSystem(int mode);  /* FILEIO.C:62 */
void InitAccessInfo(void);  /* FILEIO.C:106 */
static void cbAccess(void);  /* FILEIO.C:115 */
void PrepareAccess(void);  /* FILEIO.C:144 */
unsigned long * FileRead(unsigned char *filename);  /* FILEIO.C:156 */
unsigned long * PathFileRead(unsigned char *path, unsigned char *name);  /* FILEIO.C:185 */
int FileWrite(unsigned char *filename, void *data, long size);  /* FILEIO.C:197 */
unsigned long * LoadFromDEVPC(unsigned char *filename);  /* FILEIO.C:214 */
unsigned long * LoadFromMEMORY(unsigned char *filename);  /* FILEIO.C:247 */
unsigned long * LoadFromCDROM(unsigned char *filename);  /* FILEIO.C:296 */
struct Humanoid * CreateHumanoid(short type, unsigned long *mad);  /* HUMAN.C:36 */
void KillAllHumanoid(void);  /* HUMAN.C:71 */
void KillHumanoid(struct Humanoid *human);  /* HUMAN.C:78 */
short ControlAllHumanoid(void);  /* HUMAN.C:97 */
void ControlHumanoid(struct Humanoid *human);  /* HUMAN.C:107 */
short DefaultActionHumanoid(struct Humanoid *human);  /* HUMAN.C:155 */
struct Humanoid * GetHumanoid(short type);  /* HUMAN.C:334 */
void MoveHumanoid(struct Humanoid *human, short ordr, short side);  /* HUMAN.C:349 */
void GetMoveSpeed(struct SVECTOR *vect, short ry, short ordr, short side);  /* HUMAN.C:370 */
short GetDirection(long dx, long dz, short roty);  /* HUMAN.C:381 */
long GetTargetDistance(struct Humanoid *human, short *deg);  /* HUMAN.C:394 */
struct Humanoid * GetNearestHumanoid(struct Humanoid *human, short distance);  /* HUMAN.C:408 */
short SearchTarget(struct Humanoid *human, long *distance, short *degree);  /* HUMAN.C:436 */
struct TraceLine * SetupTraceLine(struct Humanoid *human, struct TracePoint *point);  /* HUMAN.C:488 */
short RestartTraceLine(struct Humanoid *human);  /* HUMAN.C:510 */
short ControlTraceLine(struct Humanoid *human);  /* HUMAN.C:526 */
void InitializeImage(void);  /* IMAGES.C:32 */
struct GsIMAGE * GetImage(int index);  /* IMAGES.C:52 */
int GetImageReady(void);  /* IMAGES.C:72 */
void InitSprite(struct GsIMAGE *image, struct GsSPRITE *sprite);  /* IMAGES.C:79 */
void SetupImageToPolyFT4(struct GsIMAGE *image, struct POLY_FT4 *ply, short x, short y);  /* IMAGES.C:106 */
void SetupImageToPolyGT4(struct GsIMAGE *image, struct POLY_GT4 *ply, short x, short y);  /* IMAGES.C:129 */
unsigned long * GetArcData(int index);  /* IMAGES.C:158 */
void SetCDVolume(void);  /* IMAGES.C:428 */
void _PlayMusic(int MusicNo, int mode);  /* IMAGES.C:438 */
void PlayMusic(int MusicNo, int mode);  /* IMAGES.C:476 */
void PlayVoice(int id);  /* IMAGES.C:485 */
void PlayMusicFormID(int id);  /* IMAGES.C:524 */
void StopMusic(void);  /* IMAGES.C:540 */
int ReqLifeBar(struct Humanoid *h);  /* INFOVIEW.C:89 */
void InitializeInfoView(void);  /* INFOVIEW.C:119 */
void PutNumber(int x, int y, int cols, int n);  /* INFOVIEW.C:197 */
static void PutStrain(void);  /* INFOVIEW.C:218 */
static void PutLifeBar(int x, int y, int n, int mx, int style);  /* INFOVIEW.C:292 */
static int PutLifeBarS(void);  /* INFOVIEW.C:328 */
void PutItemIcon(int ItemID, short x, short y, short scale);  /* INFOVIEW.C:349 */
void PutItemCursor(short x, short y, short size, short rotdif);  /* INFOVIEW.C:358 */
static void PutItemList(void);  /* INFOVIEW.C:366 */
void SaveSI(int target, unsigned char *name, void *mem, long size);  /* INFOVIEW.C:525 */
void * LoadSI(int target, unsigned char *name);  /* INFOVIEW.C:618 */
void SelectStage(void);  /* INFOVIEW.C:675 */
static void AddEnemy(void);  /* INFOVIEW.C:695 */
static void SelectCameraOwnerOption(void);  /* INFOVIEW.C:796 */
static void LayoutEnemyOption(void);  /* INFOVIEW.C:849 */
static void AddItem2(void);  /* INFOVIEW.C:958 */
static void FileOption(void);  /* INFOVIEW.C:1021 */
void PlayerOption(void);  /* INFOVIEW.C:1144 */
void LoadExecEx(unsigned char *file, unsigned long stack, unsigned long size);  /* INFOVIEW.C:1173 */
void DemoPatchInit(void);  /* INFOVIEW.C:1196 */
void DemoPatchProc(void);  /* INFOVIEW.C:1208 */
static void DrawPause(void);  /* INFOVIEW.C:1224 */
static void PauseProc(void);  /* INFOVIEW.C:1261 */
static void PutMap(void);  /* INFOVIEW.C:1322 */
void ResetInfoview(int stage);  /* INFOVIEW.C:1391 */
void DoInfoViewProc(void);  /* INFOVIEW.C:1413 */
static struct Humanoid * SearchItemTarget2(struct Humanoid *owner, struct SVECTOR *rot, struct VECTOR *start, struct VECTOR *target);  /* ITEM.C:352 */
void ClearItemLayout(void);  /* ITEM.C:461 */
void PackItemLayout(void *buf, long size);  /* ITEM.C:473 */
void RestoreItemLayout(void *buf);  /* ITEM.C:507 */
void InitializeItem(void);  /* ITEM.C:533 */
struct tag_TItem * GetFreeItemSlot(void);  /* ITEM.C:577 */
enum TItemType GetItemType(int ConflictID);  /* ITEM.C:601 */
int RequestItem(enum TRequestItem req, void *param);  /* ITEM.C:617 */
static void MoveKorogari(struct tag_TItem *item, struct param_korogari *param);  /* ITEM.C:663 */
static void MoveFly(struct tag_TItem *item, struct param_fly *param);  /* ITEM.C:742 */
static void SetupFly(struct param_fly *pfly, struct VECTOR *start, struct VECTOR *end, int yw, int yh, int time);  /* ITEM.C:792 */
void ProcItemDrop(struct tag_TItem *item);  /* ITEM.C:835 */
int ReqItemDrop(struct PARAM_ITEM_LAUNCH *p);  /* ITEM.C:907 */
void ProcSightShot(struct tag_TItem *item);  /* ITEM.C:939 */
void ProcKaginawa(struct tag_TItem *item);  /* ITEM.C:1026 */
void ProcItemTeleport(struct tag_TItem *item);  /* ITEM.C:1097 */
int ReqItemStay(struct PARAM_ITEM_STAY *p);  /* ITEM.C:1140 */
void ProcItemMakibishi(struct tag_TItem *item);  /* ITEM.C:1171 */
int ReqItemMakibishi(struct PARAM_ITEM_DROP *p);  /* ITEM.C:1235 */
static void ProcItemManebue(struct tag_TItem *item);  /* ITEM.C:1256 */
static int ReqItemManebue(struct PARAM_ITEM_LAUNCH *p);  /* ITEM.C:1290 */
void ProcItemShinsoku(struct tag_TItem *item);  /* ITEM.C:1324 */
static int ReqItemShinsoku(struct PARAM_ITEM_LAUNCH *p);  /* ITEM.C:1383 */
void ProcItemSmoke(struct tag_TItem *item);  /* ITEM.C:1400 */
int ReqItemSmoke(struct PARAM_ITEM_LAUNCH *p);  /* ITEM.C:1463 */
void ProcItemKusuri(struct tag_TItem *item);  /* ITEM.C:1485 */
static int ReqItemKusuri(struct PARAM_ITEM_LAUNCH *p);  /* ITEM.C:1549 */
void ProcItemKawarimi(struct tag_TItem *item);  /* ITEM.C:1571 */
static int ReqItemKawarimi(struct PARAM_ITEM_LAUNCH *p);  /* ITEM.C:1610 */
void ProcItemDokudango(struct tag_TItem *item);  /* ITEM.C:1632 */
static int ReqItemDokudango(struct PARAM_ITEM_LAUNCH *p);  /* ITEM.C:1777 */
void ProcItemGosin(struct tag_TItem *item);  /* ITEM.C:1804 */
static int ReqItemGosin(struct PARAM_ITEM_LAUNCH *p);  /* ITEM.C:1860 */
static void ProcItemNingyo(struct tag_TItem *item);  /* ITEM.C:1882 */
static int ReqItemNingyo(struct PARAM_ITEM_LAUNCH *p);  /* ITEM.C:2018 */
static void ProcItemHenshin(struct tag_TItem *item);  /* ITEM.C:2060 */
static int ReqItemHenshin(struct PARAM_ITEM_LAUNCH *p);  /* ITEM.C:2204 */
static void ProcItemGoshikimai(struct tag_TItem *item);  /* ITEM.C:2223 */
static int ReqItemGoshikimai(struct PARAM_ITEM_LAUNCH *p);  /* ITEM.C:2262 */
static void ProcItemKaengeki(struct tag_TItem *item);  /* ITEM.C:2287 */
static int ReqItemKaengeki(struct PARAM_ITEM_LAUNCH *p);  /* ITEM.C:2344 */
static void ProcItemNinken(struct tag_TItem *item);  /* ITEM.C:2368 */
static int ReqItemNinken(struct PARAM_ITEM_LAUNCH *p);  /* ITEM.C:2461 */
void ProcItemHappou(struct tag_TItem *item);  /* ITEM.C:2486 */
static int ReqItemHappou(struct PARAM_ITEM_LAUNCH *p);  /* ITEM.C:2541 */
void ProcItemFire(struct tag_TItem *item);  /* ITEM.C:2586 */
int ReqItemFire(struct PARAM_ITEM_LAUNCH *p);  /* ITEM.C:2706 */
void ProcItemNemuri(struct tag_TItem *item);  /* ITEM.C:2738 */
int ReqItemNemuri(struct PARAM_ITEM_LAUNCH *p);  /* ITEM.C:2835 */
void ProcItemLightningBolt(struct tag_TItem *item);  /* ITEM.C:2856 */
int ReqItemLightningBolt(struct PARAM_ITEM_LAUNCH *p);  /* ITEM.C:2917 */
void ProcItemGun(struct tag_TItem *item);  /* ITEM.C:2938 */
void ProcItemNapalm(struct tag_TItem *item);  /* ITEM.C:3014 */
void ProcItemLaunch(struct tag_TItem *item);  /* ITEM.C:3089 */
static void UpdateItemState(void);  /* ITEM.C:3176 */
void DoItemProc(void);  /* ITEM.C:3205 */
void ReqItemDefault(struct Humanoid *user, enum TItemType ItemID);  /* ITEM.C:3261 */
int ReqItemLaunch(struct PARAM_ITEM_LAUNCH *p);  /* ITEM.C:3289 */
static void ArrangeLocalMatrix(struct ModelType *model, struct MATRIX *t);  /* ITEM.C:3328 */
void ProcItemArrow(struct tag_TItem *item);  /* ITEM.C:3367 */
int ReqItemArrow(struct PARAM_ITEM_LAUNCH *p);  /* ITEM.C:3488 */
static void CalcWorldVector(struct ModelArchiveType *model, struct VECTOR *v);  /* ITEM.C:3508 */
void ProcItemJirai(struct tag_TItem *item);  /* ITEM.C:3527 */
int ReqItemJirai(struct PARAM_ITEM_DROP *p);  /* ITEM.C:3609 */
int ReqItemUse(struct PARAM_ITEM_LAUNCH *p);  /* ITEM.C:3631 */
void TurnAroundAllItems(struct Humanoid *user);  /* ITEM.C:4023 */
short ChkCard(void);  /* MEMCARD.C:84 */
short DeleteCard(unsigned char *name);  /* MEMCARD.C:95 */
short FormatCard(void);  /* MEMCARD.C:108 */
short LoadCard(int target, unsigned char *name);  /* MEMCARD.C:119 */
short SaveCard(int target, unsigned char *name, void *mem, long size);  /* MEMCARD.C:157 */
void ResetAllMisc(void);  /* MISC.C:147 */
void InitMisc(void);  /* MISC.C:162 */
static void ProcMiscFire(struct tag_TMisc *m, enum TMiscMessage msg);  /* MISC.C:249 */
static void ProcMiscDoor(struct tag_TMisc *m, enum TMiscMessage msg);  /* MISC.C:294 */
static void ProcMiscPitfall(struct tag_TMisc *m, enum TMiscMessage msg);  /* MISC.C:414 */
static void ProcMiscSnowfall(struct tag_TMisc *m, enum TMiscMessage msg);  /* MISC.C:525 */
static void ProcMiscSprite(struct tag_TMisc *m, enum TMiscMessage msg);  /* MISC.C:582 */
void AddMisc(enum MiscType type, int x, int y, int z, int a, int b, int c);  /* MISC.C:636 */
void DoMiscProc(void);  /* MISC.C:713 */
void InitMoji(int x, int y);  /* MOJI.C:79 */
unsigned char * GetKazu(unsigned char *sScript, int wk1, int wk2);  /* MOJI.C:130 */
void PutMojiColKage(int x, int y, int col, unsigned char *Script, unsigned int flag2, int selichi);  /* MOJI.C:149 */
void PutMojiCol(int x, int y, int col, unsigned char *Script, unsigned int flag2, int selichi);  /* MOJI.C:179 */
void PutMojiKage(int x, int y, unsigned char *Script, unsigned int flag2, int selichi);  /* MOJI.C:203 */
void PutMoji(int x, int y, unsigned char *Script, unsigned int flag2, int selichi);  /* MOJI.C:231 */
void HumanActionControl(struct Humanoid *human);  /* MOTION.C:145 */
short MotionAndMove(void);  /* MOTION.C:173 */
short SetNowMotion(struct Humanoid *human, short mid, short move);  /* MOTION.C:188 */
short NowReturnNormal(struct Humanoid *human);  /* MOTION.C:200 */
void ReturnNormal(void);  /* MOTION.C:210 */
short SwimCheck(void);  /* MOTION.C:219 */
short FallCheck(void);  /* MOTION.C:256 */
short HangCheck(void);  /* MOTION.C:291 */
struct MapVector * StickonCheck(void);  /* MOTION.C:346 */
void JumpControl(void);  /* MOTION.C:367 */
void DamageControl(void);  /* MOTION.C:408 */
void AttackControl(void);  /* MOTION.C:648 */
void AttackCancelControl(short mode);  /* MOTION.C:726 */
short AttackContinuousCheck(struct BattleType *battle);  /* MOTION.C:755 */
void WeaponHitWeapon(struct ModelType *hand);  /* MOTION.C:771 */
void AttackBowControl(void);  /* MOTION.C:800 */
void AttackGunControl(short length, short frm);  /* MOTION.C:832 */
void AttackPQD(short sfrm, short efrm);  /* MOTION.C:849 */
void AttackFire(short sfrm, short efrm);  /* MOTION.C:876 */
void ItemControl(void);  /* MOTION.C:896 */
void ActNORMAL(void);  /* MOTION.C:916 */
void ActACTION(void);  /* MOTION.C:963 */
void ActMOVE(void);  /* MOTION.C:994 */
void ActSWIM(void);  /* MOTION.C:1030 */
void ActKAGI(void);  /* MOTION.C:1091 */
void ActENGAGE(void);  /* MOTION.C:1181 */
void ActCHASE(void);  /* MOTION.C:1241 */
void ActATTACK(void);  /* MOTION.C:1306 */
void ActSTATE(void);  /* MOTION.C:1507 */
void ActJUMP(void);  /* MOTION.C:1590 */
void ActHANG(void);  /* MOTION.C:1663 */
void ActSQUAT(void);  /* MOTION.C:1712 */
void ActSTICKON(void);  /* MOTION.C:1799 */
void ActCEILHANG(void);  /* MOTION.C:1903 */
void ActSYURI(void);  /* MOTION.C:1908 */
void ActITEM(void);  /* MOTION.C:1949 */
void ActDAMAGE(void);  /* MOTION.C:1989 */
void ActDEAD(void);  /* MOTION.C:2046 */
int CdaGetCurrentLength(void);  /* OPAUDIO.C:29 */
int CdaReady(void);  /* OPAUDIO.C:46 */
static void cbCheckCD(void);  /* OPAUDIO.C:69 */
int CdaPlayXA(unsigned char *fname, struct CdlLOC *start, struct CdlLOC *end, unsigned char channel, int mode);  /* OPAUDIO.C:133 */
void CdaStop(void);  /* OPAUDIO.C:176 */
void ReadSaveData(void);  /* OPENING.C:196 */
void WriteSaveData(void);  /* OPENING.C:222 */
void StartLoad(void);  /* OPENING.C:244 */
void SpWorkSet(struct GsSPRITE *spptr, struct GsIMAGE *img, int x, int y, int rgb, int attri);  /* OPENING.C:302 */
void GsSortSpriteKage(struct GsSPRITE *gspOp7, short z, short flag);  /* OPENING.C:326 */
short FideOutFs(short mode, short x, short y, short w, int h);  /* OPENING.C:351 */
short FideOut(short job);  /* OPENING.C:383 */
short FideOut2(short sjob);  /* OPENING.C:434 */
short FideOut3(short sjob);  /* OPENING.C:455 */
short Opening(short job);  /* OPENING.C:480 */
int open_stream(unsigned char *fname, int x, int y, int mode);  /* OPMOVIE.C:129 */
int get_stream(void);  /* OPMOVIE.C:181 */
void close_stream(void);  /* OPMOVIE.C:247 */
static int strSetDefDecEnv(struct DECENV *dec, int x, int y);  /* OPMOVIE.C:272 */
static int strInit(struct CdlLOC *loc, void (*callback)());  /* OPMOVIE.C:300 */
void strCallback(void);  /* OPMOVIE.C:323 */
static int strNextVlc(struct DECENV *dec);  /* OPMOVIE.C:389 */
static unsigned long * strNext(struct DECENV *dec);  /* OPMOVIE.C:412 */
static void strSync(struct DECENV *dec, int mode);  /* OPMOVIE.C:457 */
static void strKickCD(struct CdlLOC *loc);  /* OPMOVIE.C:478 */
void InitPadControl(void);  /* PADCMD.C:82 */
void PadShock(int port, int p1, int p2);  /* PADCMD.C:109 */
void ComPad(int port, unsigned char *rxbuf);  /* PADCMD.C:136 */
void PadShockAR(int port, int pow, int attack, int release);  /* PADCMD.C:241 */
void PadProc(void);  /* PADCMD.C:249 */
long GetRealPad(int port);  /* PADCMD.C:276 */
void GetPadXY(short no, short *x, short *y);  /* PADCMD.C:285 */
short GetPad(short no);  /* PADCMD.C:293 */
short SetPad(struct PADtype *pad, short data);  /* PADCMD.C:311 */
short GetCommand(struct PADtype *pad);  /* PADCMD.C:333 */
short SetCommand(struct PADtype *pad, short cmd);  /* PADCMD.C:359 */
void SetupSoundEffect(short mode, short stage);  /* SEMNG.C:26 */
short SoundEx(struct VECTOR *locate, short seid);  /* SEMNG.C:42 */
short Sound(struct Humanoid *human, short seid);  /* SEMNG.C:61 */
void SetupStageSequence(void);  /* STAGE.C:77 */
void StartStageSequence(void);  /* STAGE.C:93 */
short StageSequence(void);  /* STAGE.C:153 */
void UpdateEvent(short n, short id);  /* STAGE.C:249 */
void MakeArcData(unsigned long *ArcData);  /* START.C:51 */
short LoadTIMarc(unsigned long *adr);  /* START.C:65 */
int main(void);  /* START.C:102 */
void StateTransition(struct Humanoid *human);  /* THINK.C:99 */
void SetupThinkFunction(struct Humanoid *human, short type);  /* THINK.C:212 */
short ThinkBasicNone(void);  /* THINK.C:229 */
short ThinkBasicHuman1(void);  /* THINK.C:236 */
short ThinkBasicHuman2(void);  /* THINK.C:247 */
short GotoPosition(long vx, long vz);  /* THINK.C:254 */
short ChasetoTarget(long length);  /* THINK.C:269 */
short Think1trace(void);  /* THINK_1.C:16 */
short Think1watch(void);  /* THINK_1.C:50 */
short Think1random(void);  /* THINK_1.C:74 */
short Think1ninja(void);  /* THINK_1.C:99 */
short Think1sleep(void);  /* THINK_1.C:106 */
short Think1chase(void);  /* THINK_1.C:119 */
short Think1target(void);  /* THINK_1.C:154 */
short Think2confirm(void);  /* THINK_2.C:14 */
short Think2contact(void);  /* THINK_2.C:21 */
short Think3callaid(void);  /* THINK_3.C:31 */
short Think3chase(void);  /* THINK_3.C:60 */
short Think3attack(void);  /* THINK_3.C:70 */
short Think3escape(void);  /* THINK_3.C:103 */
short Think3area(void);  /* THINK_3.C:128 */
short Think3hitaway(void);  /* THINK_3.C:172 */
short Think3firstattack(void);  /* THINK_3.C:209 */
static short ItemUse(void);  /* THINK_3.C:225 */
static short SuccessionAttack(long dist, short deg);  /* THINK_3.C:247 */
static short AttackShort(void);  /* THINK_3.C:266 */
static short AttackGeneral(void);  /* THINK_3.C:368 */
static short AttackLong(void);  /* THINK_3.C:450 */
static short AttackIndirect(void);  /* THINK_3.C:525 */
static short AttackAnimal(void);  /* THINK_3.C:583 */
short Think4abandon(void);  /* THINK_4.C:14 */
short Think4contact(void);  /* THINK_4.C:36 */
short Think4chase(void);  /* THINK_4.C:75 */
void vinit(void *adr, unsigned long size);  /* VALLOC.C:33 */
unsigned long vgetmaxsize(void);  /* VALLOC.C:45 */
unsigned long vgetfreesize(void);  /* VALLOC.C:61 */
void * valloc(unsigned long size);  /* VALLOC.C:76 */
void * vrealloc(void *pt, unsigned long size);  /* VALLOC.C:130 */
void * vcalloc(unsigned long size, unsigned char c);  /* VALLOC.C:203 */
void vfree(void *pt);  /* VALLOC.C:216 */
unsigned long vsize(void *pt);  /* VALLOC.C:247 */
void * vmemoryGC(void *pt);  /* VALLOC.C:259 */
void SystemOut(unsigned char *string);  /* VALLOC.C:305 */
void CreateStage(int StageNo, int CharType);  /* WORLD.C:139 */
struct OrnamentArchiveType * LoadOrnamentArchive(unsigned long *adr, struct ModelType *prnt);  /* WORLD.C:259 */
void DisposeOrnamentArchive(struct OrnamentArchiveType *mad);  /* WORLD.C:319 */
static void GetCenterAndSize(unsigned long *tmd, struct SVECTOR *center, int *size);  /* WORLD.C:390 */
static short LoadConstruction(unsigned long *data);  /* WORLD.C:436 */
static long PointInTri(struct TPoint *pt);  /* WORLD.C:661 */
int IsVisible(long x, long y, long z, long s);  /* WORLD.C:685 */
void ActivateHumans(void);  /* WORLD.C:752 */
void DrawConstruction(void);  /* WORLD.C:798 */
void leResetEnemyLayout(void);  /* WORLD.C:1054 */
void leClearLayout(void);  /* WORLD.C:1065 */
int leFindEnemy(void);  /* WORLD.C:1099 */
int leSetEnemy(int type, short think, long x, long y, long z, int r);  /* WORLD.C:1134 */
static void DestroyTraceLine(struct TraceLine *t);  /* WORLD.C:1186 */
void leLayoutEnemy(int mode);  /* WORLD.C:1197 */
int leRemoveEnemy(void);  /* WORLD.C:1259 */
void lePackEnemyLayout(void *buf, long size);  /* WORLD.C:1275 */
void leRestoreEnemyLayout(void *buf);  /* WORLD.C:1286 */
void leResetPath(int id);  /* WORLD.C:1293 */
void leAddPath(int id, long x, long y, long z);  /* WORLD.C:1303 */
void jt_init4(void);  /* WORLD.C:1329 */
