options:
  platform: psx
  basename: main.exe
  base_path: ..
  build_path: .shake/build/main.exe
  target_path: disks/tenchu/main.exe
  asm_path: .shake/gen/main.exe/asm
  asset_path: .shake/gen/main.exe/assets
  src_path: .shake/gen/main.exe/src
  compiler: GCC
  find_file_boundaries: yes
  use_legacy_include_asm: no
  migrate_rodata_to_functions: no
  ld_script_path: .shake/gen/main.exe/linker/main.exe.ld
  symbol_addrs_path: config/symbols.main.exe.txt
  # undefined_syms_path: meta/undefined_symbols.main.exe.txt
  undefined_funcs_auto_path: .shake/gen/main.exe/meta/undefined_functions_auto.main.exe.txt
  undefined_syms_auto_path: .shake/gen/main.exe/meta/undefined_symbols_auto.main.exe.txt
  generated_c_preamble: |
    #include "common.h"
    #include "main.exe.h"

  section_order:
    # - ".rodata"
    # - ".text"
    # - ".data"
    - ".rodata"
    - ".text"
    - ".data"
    - ".sdata"
    - ".sbss"
    - ".bss"

segments:
  - [0x800, header]
  # - [0x84, bin, zeroPadding] # Zero Padding
  - name: main.exe
    type: code
    start: 0x00000800
    vram: 0x80011000
    # vram: 0x80016134
    subalign: 4
    subsegments:
      - [0x800, data] # ?
      - [0x5934, c]
      - [0x4F9E4, c]
      - [0x4F9F4, c]
      - [0x4FF04, c]
      - [0x52774, c]
      - [0x53144, c]
      - [0x53874, c]
      - [0x53954, c]
      - [0x539F4, c]
      - [0x53BC4, c]
      - [0x540C4, c]
      - [0x54734, c]
      - [0x547B4, c]
      - [0x54864, c]
      - [0x54C24, c]
      - [0x54C34, c]
      - [0x54CD4, c]
      - [0x54D54, c]
      - [0x55354, c]
      - [0x553D4, c]
      - [0x55424, c]
      - [0x55454, c]
      - [0x55484, c]
      - [0x554E4, c]
      - [0x55534, c]
      - [0x55624, c]
      - [0x556F4, c]
      - [0x55704, c]
      - [0x55D74, c]
      - [0x56034, c]
      - [0x56304, c]
      - [0x582F4, c]
      - [0x59894, c]
      - [0x5B034, c]
      - [0x5BAC4, c]
      - [0x5CF54, c]
      - [0x5D924, c]
      - [0x5E1E4, c]
      - [0x5E294, c]
      - [0x5E2F4, c]
      - [0x5E3E4, c]
      - [0x5E824, c]
      - [0x5E994, c]
      - [0x5EE14, c]
      - [0x5EEB4, c]
      - [0x5EEE4, c]
      - [0x5F5D4, c]
      - [0x5F684, c]
      - [0x5F784, c]
      - [0x5F9C4, c]
      - [0x5FAD4, c]
      - [0x5FC24, c]
      - [0x5FE44, c]
      - [0x5FFF4, c]
      - [0x603B4, c]
      - [0x60B54, c]
      - [0x60B64, c]
      - [0x60FF4, c]
      - [0x61344, c]
      - [0x61504, c]
      - [0x61B54, c]
      - [0x62834, c]
      - [0x62954, c]
      - [0x62DA4, c]
      - [0x62E94, c]
      - [0x63014, c]
      - [0x63024, c]
      - [0x63034, c]
      - [0x63B74, c]
      - [0x63BA4, c]
      - [0x63C24, c]
      - [0x63C34, c]
      - [0x63C44, c]
      - [0x63CA4, c]
      - [0x63F74, c]
      - [0x642F4, c]
      - [0x64324, c]
      - [0x645E4, c]
      - [0x64634, c]
      - [0x64664, c]
      - [0x64804, c]
      - [0x64924, c]
      - [0x64AE4, c]
      - [0x64B44, c]
      - [0x64BA4, c]
      - [0x64C84, c]
      - [0x64C94, c]
      - [0x65054, c]
      - [0x65654, c]
      - [0x65874, c]
      - [0x658A4, c]
      - [0x65914, c]
      - [0x65964, c]
      - [0x659A4, c]
      - [0x65A14, c]
      - [0x65AC4, c]
      - [0x65B34, c]
      - [0x65B84, c]
      - [0x65BC4, c]
      - [0x65CF4, c]
      - [0x66394, c]
      - [0x66654, c]
      - [0x66F44, c]
      - [0x66FA4, c]
      - [0x67074, c]
      - [0x671A4, c]
      - [0x67234, c]
      - [0x674E4, c]
      - [0x675F4, c]
      - [0x678D4, c]
      - [0x679E4, c]
      - [0x67AF4, c]
      - [0x67B54, c]
      - [0x67B84, c]
      - [0x67CC4, c]
      - [0x67E94, c]
      - [0x67EF4, c]
      - [0x67F04, c]
      - [0x67F34, c]
      - [0x67F64, c]
      - [0x67FE4, c]
      - [0x682B4, c]
      - [0x68544, c]
      - [0x68A54, c]
      - [0x69024, c]
      - [0x695D4, c]
      - [0x69C94, c]
      - [0x6A8E4, c]
      - [0x6AF24, c]
      - [0x6B694, c]
      - [0x6B814, c]
      - [0x6B904, c]
      - [0x6BB24, c]
      - [0x6BB34, c]
      - [0x6C214, c]
      - [0x6C224, c]
      - [0x6C234, c]
      - [0x6C244, c]
      - [0x6C2C4, c]
      - [0x6C3E4, c]
      - [0x6C684, c]
      - [0x6C6B4, c]
      - [0x6D3D4, c]
      - [0x703E4, c]
      - [0x703F4, c]
      - [0x70434, c]
      - [0x70454, c]
      - [0x70494, c]
      - [0x704B4, c]
      - [0x704E4, c]
      - [0x70504, c]
      - [0x70524, c]
      - [0x70544, c]
      - [0x70564, c]
      - [0x70584, c]
      - [0x71F64, c]
      - [0x71F74, c]
      - [0x71F84, c]
      - [0x71F94, c]
      - [0x71FA4, c]
      - [0x71FB4, c]
      - [0x71FC4, c]
      - [0x72264, c]
      - [0x72274, c]
      - [0x72284, c]
      - [0x72294, c]
      - [0x722A4, c]
      - [0x722B4, c]
      - [0x722F4, c]
      - [0x72404, c]
      - [0x72AC4, c]
      - [0x72B94, c]
      - [0x72E94, c]
      - [0x72EA4, c]
      - [0x72EB4, c]
      - [0x72EC4, c]
      - [0x72ED4, c]
      - [0x72EE4, c]
      - [0x72EF4, c]
      - [0x72F94, c]
      - [0x73004, c]
      - [0x73014, c]
      - [0x73024, c]
      - [0x73734, c]
      - [0x74D94, c]
      - [0x75384, c]
      - [0x759E4, c]
      - [0x75EA4, c]

      # - [0x4C8D4, c]
      - [0x75F64, data]
      - [0x86E98, sdata]
      - [0x87788, sbss]
      # Ghidra says there's bss starting from 0x87790 but it's all zero. bss is
      # by definition uninitialised memory so linker won't put anything here.
      # Yet then original binary has zeroes here. So we just remove this
      # subsegment and let it be part of .sbss which will explicitly insert
      # zeroes and make the binary match.
      # - [0x87790, bss]
  - [0x87800]
