#!/usr/bin/env python3
"""Generate a splat config for a PS-EXE we have not started decompiling.

Tenchu ships six executables. `main.exe` is the one we are matching; the others
(`menu.exe`, `ending.exe`, `trial.exe`, `run.exe`, and the boot stub
`slps_019.01`) are still whole. This writes each a splat config that splits it
into one big `data` blob and reassembles it byte-identically, so the build system
carries them from day one and a function can be carved out of any of them later
with the same `tools/reverse.py` workflow.

    tools/newexe.py menu.exe ending.exe trial.exe run.exe slps_019.01
    tools/newexe.py --all

Writes `config/splat.<name>.yaml` and an empty `config/symbols.<name>.txt`.
Refuses to overwrite a config that has real subsegments in it (i.e. one somebody
has started carving), unless you pass --force.

The next stage is `tools/scaffold_exe.py`, which rewrites a blob config into
per-function INCLUDE_ASM stubs named from `reference/xexe-<name>.tsv` — the
decomp-ready shape menu.exe/ending.exe/trial.exe carry now.
"""
from __future__ import annotations

import argparse, os, re, struct, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)

# name -> path of the original image
IMAGES = {
    "main.exe": "disks/tenchu/main.exe",
    "menu.exe": "disks/tenchu/menu.exe",
    "ending.exe": "disks/tenchu/ending.exe",
    "trial.exe": "disks/tenchu/trial.exe",
    "run.exe": "disks/tenchu/run.exe",
    "slps_019.01": "disks/slps_019.01",
}



def psx_exe_info(path: str) -> dict:
    d = open(path, "rb").read()
    if d[:8] != b"PS-X EXE":
        sys.exit(f"{path}: not a PS-EXE")
    pc0, gp0 = struct.unpack_from("<II", d, 0x10)
    t_addr, t_size = struct.unpack_from("<II", d, 0x18)
    if 0x800 + t_size != len(d):
        sys.exit(f"{path}: header t_size {t_size:#x} + 0x800 != file size {len(d):#x}")
    # $gp is set by code, not the header (gp0 is 0 in every Tenchu exe). Find the
    # one `lui $gp / addiu $gp,$gp` pair in .text.
    text = d[0x800:0x800 + t_size]
    gp = None
    for i in range(0, len(text) - 4, 4):
        w = struct.unpack_from("<I", text, i)[0]
        if (w >> 26) == 15 and ((w >> 16) & 31) == 28:      # lui $gp
            w2 = struct.unpack_from("<I", text, i + 4)[0]
            if (w2 >> 26) == 9 and ((w2 >> 21) & 31) == 28 and ((w2 >> 16) & 31) == 28:
                lo = w2 & 0xFFFF
                gp = ((w & 0xFFFF) << 16) + (lo - 0x10000 if lo & 0x8000 else lo)
                break
    return dict(size=len(d), t_addr=t_addr, t_size=t_size, pc0=pc0, gp=gp)


def config(name: str, img: str, info: dict) -> str:
    seg = name.replace(".", "_").replace("-", "_")
    gp = f"  gp_value: {info['gp']:#x}\n" if info["gp"] else ""
    return f'''# Generated by tools/newexe.py -- {name} is not decompiled yet.
#
# One `textbin` subsegment covering the whole image: splat .incbin's it and the build
# reassembles it byte-identically. Carve a function out of it exactly as for main.exe
# (tools/reverse.py) and this file grows `c` subsegments the same way.
#
# `textbin`, not `data`: splat groups a segment's subsegments by SECTION (per
# `section_order`), not by address, so a `c` subsegment's .text would be emitted
# after every `data` blob's .data and shift the whole image. textbin puts the raw
# bytes in .text, where they interleave with carved C in address order.
# (main.exe gets away with `data` only because all its data precedes all its code.)
options:
  platform: psx
  basename: {name}
  base_path: ..
  build_path: .shake/build/{name}
  target_path: {img}
  asm_path: .shake/gen/{name}/asm
  asset_path: .shake/gen/{name}/assets
  src_path: .shake/gen/{name}/src
  compiler: GCC
  find_file_boundaries: no
  use_legacy_include_asm: no
  migrate_rodata_to_functions: no
  # include/{{macro,labels,gte_macros}}.inc and include_asm.h are checked-in sources
  # (config/splat.main.exe.yaml documents how to regenerate them). Six configs all
  # writing them would race; nobody writes them.
  generate_asm_macros_files: no
{gp}  ld_script_path: .shake/gen/{name}/linker/{name}.ld
  symbol_addrs_path: config/symbols.{name}.txt
  undefined_funcs_auto_path: .shake/gen/{name}/meta/undefined_functions_auto.{name}.txt
  undefined_syms_auto_path: .shake/gen/{name}/meta/undefined_symbols_auto.{name}.txt
  generated_c_preamble: |
    #include "common.h"
  string_encoding: ASCII
  section_order:
    - .data
    - .text
    - .rodata
    - .sdata
    - .sbss
    - .bss

segments:
  - [0x800, header]
  - name: {seg}
    type: code
    align: 4
    start: 0x00000800
    vram: {info['t_addr']:#010x}
    subalign: 4
    subsegments:
      - [0x800, textbin]
  - [{info['size']:#x}]
'''


def already_carved(path: str) -> bool:
    if not os.path.exists(path):
        return False
    return bool(re.search(r"^\s+- \[0x[0-9A-Fa-f]+,\s*c,", open(path).read(), re.M))


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("names", nargs="*", choices=sorted(IMAGES) + [], metavar="NAME")
    ap.add_argument("--all", action="store_true")
    ap.add_argument("--force", action="store_true")
    args = ap.parse_args()
    names = sorted(IMAGES) if args.all else args.names
    if not names:
        ap.error("give exe names, or --all")

    for name in names:
        img = IMAGES[name]
        if not os.path.exists(img):
            print(f"  {name:14s} SKIP (missing {img})")
            continue
        cfg = f"config/splat.{name}.yaml"
        if already_carved(cfg) and not args.force:
            print(f"  {name:14s} SKIP ({cfg} already has `c` subsegments)")
            continue
        info = psx_exe_info(img)
        open(cfg, "w").write(config(name, img, info))
        syms = f"config/symbols.{name}.txt"
        if not os.path.exists(syms):
            open(syms, "w").write("")
        gp = f"{info['gp']:#x}" if info["gp"] else "none"
        print(f"  {name:14s} {info['size']:>8} bytes  vram {info['t_addr']:#010x}  "
              f"gp {gp:>10}  -> {cfg}")


if __name__ == "__main__":
    main()
