#!/usr/bin/env python3
"""Emit a PCSX-Redux Lua symbol loader from a linked ELF.

PCSX-Redux keeps one flat address->name map (``m_symbols``) that names the
debugger's disassembly, call stacks, and breakpoints.  Its Lua API is
``PCSX.insertSymbol(address, name)``; this tool turns the ELF the build just
linked into a ``-dofile`` script so every ``./Build run*`` launcher loads the
matching symbol set automatically — exact, mod, or relink layouts alike,
because the addresses come from the launched artifact's own ELF.

    tools/pcsx_symbols.py --elf .shake/build/tenchu/main.exe.elf -o main.exe.symbols.lua

Optional ``--tsv`` inputs (addr<TAB>size<TAB>name, e.g.
``config/functions.menu.exe.tsv``) add names for executables that have no
ELF yet; mixing sets whose address spaces overlap (MENU and MAIN share RAM)
is deliberately left to the caller.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import sys

try:
    from tools import psxexe
except ImportError:  # Direct execution (``tools/pcsx_symbols.py``).
    import psxexe  # type: ignore[no-redef]


def preferred(existing: str | None, candidate: str) -> str:
    """Pick one name per address, deterministically.

    Real identifiers beat auto labels (D_*, FUN_*), which beat internal
    underscore-prefixed aliases; ties break alphabetically so regeneration
    is stable.
    """
    def rank(name: str) -> tuple:
        return (
            name.startswith("__"),
            name.startswith(("D_", "FUN_")),
            name.startswith("_"),
            len(name),
            name,
        )

    if existing is None:
        return candidate
    return min(existing, candidate, key=rank)


def collect(elf: Path | None, tsvs: list[Path]) -> dict[int, str]:
    names: dict[int, str] = {}
    if elf is not None:
        metadata = psxexe.read_elf_metadata(elf)
        for name, address in metadata.symbols.items():
            if "." in name or not 0x80000000 <= address < 0x80800000:
                continue
            names[address] = preferred(names.get(address), name)
    for tsv in tsvs:
        for line in tsv.read_text().splitlines():
            if line.startswith("#"):
                continue
            parts = line.split("\t")
            if len(parts) < 3:
                continue
            address = int(parts[0], 16)
            names[address] = preferred(names.get(address), parts[2])
    return names


def emit(names: dict[int, str], source: str) -> str:
    lines = [
        f"-- generated by tools/pcsx_symbols.py from {source}; do not edit",
        "local n = 0",
    ]
    for address, name in sorted(names.items()):
        lines.append(f'PCSX.insertSymbol({address:#010x}, "{name}") n = n + 1')
    lines.append('print("tenchu: loaded " .. n .. " symbols from ' + source + '")')
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--elf", type=Path)
    parser.add_argument("--tsv", type=Path, action="append", default=[])
    parser.add_argument("-o", "--output", type=Path, required=True)
    args = parser.parse_args(argv)
    if args.elf is None and not args.tsv:
        parser.error("need --elf and/or --tsv")
    try:
        names = collect(args.elf, args.tsv)
    except (OSError, psxexe.PsxExeError) as error:
        print(f"pcsx-symbols: {error}", file=sys.stderr)
        return 1
    source = args.elf.name if args.elf else ",".join(t.name for t in args.tsv)
    args.output.write_text(emit(names, source))
    print(f"pcsx-symbols: {len(names)} symbols -> {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
