#!/usr/bin/env python3
"""Dump everything PSX.SYM knows into reviewable reference artefacts.

PSX.SYM's addresses belong to a lost build, but its *names and types* are the
original source's.  None of that needs address correlation -- it keys by name.
Writes, under reference/:

  psxsym-types.h    structs/unions/enums/typedefs with the original field names
  psxsym-protos.h   function prototypes with the original parameter names
  psxsym-tu-map.tsv function -> source file, line span, frame size, saved-reg mask
  psxsym-locals.tsv every local variable: name, type, and where it lived
  psxsym-data.tsv   data symbols (globals) with their original types
  psxsym-statics.tsv symbols the original build declared `static`

These are *reference* material, not build inputs: types.h in particular uses the
demo build's layouts, which retail may have changed.  Check a field offset
against the disassembly before trusting it.
"""
from __future__ import annotations

import argparse, collections, os, re, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import psxsym as P

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FAKE = re.compile(r"^\.\d+fake$")
REG = ["$zero", "$at", "$v0", "$v1", "$a0", "$a1", "$a2", "$a3",
       "$t0", "$t1", "$t2", "$t3", "$t4", "$t5", "$t6", "$t7",
       "$s0", "$s1", "$s2", "$s3", "$s4", "$s5", "$s6", "$s7",
       "$t8", "$t9", "$k0", "$k1", "$gp", "$sp", "$fp", "$ra"]


def stem(path: str) -> str:
    return path.split("\\")[-1].replace(".C", "").replace(".", "_")


def ident(tag: str, file: str, tagmap: dict[tuple[str, str], str]) -> str:
    """Resolve a struct tag to a C identifier.

    ``.NNNfake`` tags are the linker's names for anonymous aggregates and are
    numbered PER TRANSLATION UNIT -- `.57fake` in AUDIO.C and in 3DCTRL.C are
    unrelated types.  So they resolve through (file, tag); a real tag is global.
    """
    if not tag:
        return ""
    if FAKE.match(tag):
        hit = tagmap.get((file, tag))
        return hit if hit else f"{stem(file)}_{tag.replace('.', '_')}"
    return tag


def declare(d: P.Def, name: str, tagmap: dict[tuple[str, str], str]) -> str:
    """Full C declarator for `name` of `d`'s type.

    COFF stores up to six 2-bit derivations starting at bit 4, ordered from the
    identifier outwards: `short (*think[4])()` is ARY, then PTR, then FCN.  A
    pointer binds looser than `[]`/`()`, so it needs parentheses whenever a
    suffix is applied after it.
    """
    t = d.type
    base = P.BASE_TYPE.get(t & 0xF, f"?{t & 0xF}")
    if (t & 0xF) in (8, 9, 10):
        kw = {8: "struct", 9: "union", 10: "enum"}[t & 0xF]
        nm = ident(d.tag, d.file, tagmap)
        base = f"{kw} {nm}" if nm else kw
    dims = list(d.dims)
    decl = name
    for i in range(6):
        x = (t >> (4 + 2 * i)) & 3
        if x == P.DT_NON:
            continue
        if x == P.DT_PTR:
            decl = "*" + decl
        elif x == P.DT_ARY:
            if decl.startswith("*"):
                decl = f"({decl})"
            decl += f"[{dims.pop(0) if dims else 0}]"
        elif x == P.DT_FCN:
            if decl.startswith("*"):
                decl = f"({decl})"
            decl += "()"
    return f"{base} {decl}".rstrip()


def rettype_of(d: P.Def, tagmap: dict[tuple[str, str], str]) -> str:
    """Return type of a function symbol: its declarator minus the trailing ()."""
    return declare(d, "", tagmap).replace("()", "").strip()


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("sym", nargs="?", default=f"{REPO}/disks/demo/PSX.SYM")
    ap.add_argument("-o", "--out", default=f"{REPO}/reference")
    args = ap.parse_args()
    sf = P.load(args.sym)
    os.makedirs(args.out, exist_ok=True)

    # ---- anonymous tags (.133fake) get the name of the typedef that wraps them
    tagmap: dict[tuple[str, str], str] = {}
    for d in sf.defs:
        if d.cls == P.C_TPDEF and d.tag and FAKE.match(d.tag):
            tagmap.setdefault((d.file, d.tag), d.name)

    # ---- collect one definition per aggregate (they repeat once per TU)
    aggr: dict[str, tuple[str, int, list[P.Def]]] = {}
    cur = None
    for d in sf.defs:
        if d.cls in (P.C_STRTAG, P.C_UNTAG, P.C_ENTAG):
            kind = {P.C_STRTAG: "struct", P.C_UNTAG: "union", P.C_ENTAG: "enum"}[d.cls]
            cur = (kind, ident(d.name, d.file, tagmap), d.size, [])
        elif d.cls == P.C_EOS:
            if cur and cur[3]:
                nm = cur[1]
                if nm not in aggr or len(aggr[nm][2]) < len(cur[3]):
                    aggr[nm] = (cur[0], cur[2], cur[3])
            cur = None
        elif cur and d.cls in (P.C_MOS, P.C_MOU, P.C_MOE, P.C_FIELD):
            cur[3].append(d)

    with open(f"{args.out}/psxsym-types.h", "w") as f:
        f.write("/* Generated by tools/symdump.py from the demo's PSX.SYM.\n"
                " * Original field names and layouts, from an EARLIER BUILD than retail.\n"
                " * Reference only -- verify offsets against the disassembly.\n */\n\n")
        for nm in sorted(aggr):
            kind, size, members = aggr[nm]
            f.write(f"{kind} {nm} {{  /* size {size} */\n")
            for m in members:
                if kind == "enum":
                    f.write(f"    {m.name} = {m.offset},\n")
                    continue
                if m.cls == P.C_FIELD:
                    f.write(f"    {declare(m, m.name, tagmap)} : {m.size};"
                            f"  /* bit +{m.offset} */\n")
                else:
                    f.write(f"    {declare(m, m.name, tagmap)};  /* +0x{m.offset:x} */\n")
            f.write("};\n\n")
        seen = set()
        for d in sf.defs:
            if d.cls != P.C_TPDEF or d.name in seen:
                continue
            seen.add(d.name)
            if FAKE.match(d.tag or "") and tagmap.get((d.file, d.tag)) == d.name:
                kw = {8: "struct", 9: "union", 10: "enum"}.get(d.type & 0xF, "")
                f.write(f"typedef {kw} {d.name} {d.name};\n")
                continue
            f.write(f"typedef {declare(d, d.name, tagmap)};\n")
    print(f"wrote psxsym-types.h  ({len(aggr)} aggregates, {len(seen)} typedefs)")

    # ---- prototypes
    rettype = {d.name: d for d in sf.defs if d.cls in (P.C_EXT, P.C_STAT)}
    with open(f"{args.out}/psxsym-protos.h", "w") as f:
        f.write("/* Generated by tools/symdump.py -- original prototypes from PSX.SYM. */\n\n")
        for fn in sorted(sf.funcs, key=lambda x: (x.file, x.line)):
            r = rettype.get(fn.name)
            pre = rettype_of(r, tagmap) if r is not None else "int"
            params = ", ".join(declare(a, a.name, tagmap) for a in fn.args) or "void"
            static = "static " if r is not None and r.cls == P.C_STAT else ""
            f.write(f"{static}{pre} {fn.name}({params});"
                    f"  /* {fn.file.split(chr(92))[-1]}:{fn.line} */\n")
    print(f"wrote psxsym-protos.h ({len(sf.funcs)} prototypes, "
          f"{sum(1 for f in sf.funcs if f.args)} with named args)")

    # ---- TU map
    with open(f"{args.out}/psxsym-tu-map.tsv", "w") as f:
        f.write("#demo_addr\tsize\tfile\tline\tend_line\tsrc_lines\tfsize\tmask\t"
                "static\tname\n")
        order = sorted(sf.funcs, key=lambda x: x.addr)
        # The 0x8E end-of-function line is not trustworthy everywhere: in THINK_2.C
        # and THINK_4.C every function claims to end at the file's last line, which
        # overlaps its successors.  Only report a span when it is consistent with
        # where the next function in the same file starts.
        nextline = {}
        for src2 in {f2.file for f2 in sf.funcs}:
            fs = sorted((f2 for f2 in sf.funcs if f2.file == src2), key=lambda x: x.line)
            for j, f2 in enumerate(fs):
                nextline[f2.name] = fs[j + 1].line if j + 1 < len(fs) else None
        for i, fn in enumerate(order):
            nxt = order[i + 1].addr if i + 1 < len(order) else fn.end_addr + 8
            r = rettype.get(fn.name)
            st = "static" if r is not None and r.cls == P.C_STAT else "extern"
            nl = nextline.get(fn.name)
            ok = fn.end_line >= fn.line and (nl is None or fn.end_line < nl)
            if ok and nl is None:
                # last function in its file: nothing bounds end_line, so sanity-check
                # against code density.  Verified spans sit near 10 bytes/line; a
                # function claiming 0.4 is really reporting the file's last line.
                span0 = fn.end_line - fn.line + 1
                ok = span0 > 0 and (nxt - fn.addr) / span0 >= 2.0
            span = str(fn.end_line - fn.line + 1) if ok else "?"
            end = str(fn.end_line) if ok else "?"
            f.write(f"{fn.addr:08x}\t{nxt-fn.addr}\t{fn.file.split(chr(92))[-1]}\t{fn.line}\t"
                    f"{end}\t{span}\t{fn.fsize}\t{fn.mask & 0xFFFFFFFF:#010x}\t"
                    f"{st}\t{fn.name}\n")

    # ---- locals: the original variables, and where the demo build put them
    with open(f"{args.out}/psxsym-locals.tsv", "w") as f:
        f.write("# Every parameter and local of the 442 debug functions.\n"
                "# storage is from the DEMO build. Its local count/types are high-value\n"
                "# codegen evidence, not a retail spec: helper/API changes can replace\n"
                "# either, so retail access widths and callee ABI win.\n"
                "# C_AUTO offsets are frame-pointer relative ($fp == $sp), so the real\n"
                "# slot is sp + fsize + offset; we print the resolved sp+N.\n"
                "# A name repeated inside one function is a distinct nested-block scope.\n"
                "#function\tfile\tkind\tstorage\ttype\tname\n")
        nloc = 0
        for fn in sorted(sf.funcs, key=lambda x: (x.file, x.line)):
            src = fn.file.split(chr(92))[-1]
            for a in fn.args:
                where = REG[a.offset] if a.cls == P.C_REGPARM and a.offset < 32 else f"stack+{a.offset}"
                f.write(f"{fn.name}\t{src}\tparam\t{where}\t"
                        f"{declare(a, '', tagmap).strip()}\t{a.name}\n")
                nloc += 1
            for v in fn.lvars:
                if v.cls == P.C_REG:
                    where = REG[v.offset] if v.offset < 32 else f"reg{v.offset}"
                else:
                    raw = v.offset - (1 << 32) if v.offset >= (1 << 31) else v.offset
                    where = f"sp+{fn.fsize + raw}"
                f.write(f"{fn.name}\t{src}\t{'reg' if v.cls == P.C_REG else 'stack'}\t{where}\t"
                        f"{declare(v, '', tagmap).strip()}\t{v.name}\n")
                nloc += 1
    print(f"wrote psxsym-locals.tsv ({nloc} params+locals across "
          f"{sum(1 for f in sf.funcs if f.args or f.lvars)} functions)")
    tus = len({f.file for f in sf.funcs})
    print(f"wrote psxsym-tu-map.tsv ({len(sf.funcs)} functions across {tus} source files)")

    # ---- data symbols (plain symbols outside .text) + their types where known
    TEXT_HI = 0x8008B02B
    dtype = {d.name: d for d in sf.defs if d.cls in (P.C_EXT, P.C_STAT, P.C_USTATIC)}
    fnames = {f.name for f in sf.funcs}
    with open(f"{args.out}/psxsym-data.tsv", "w") as f:
        f.write("#demo_addr\tstorage\ttype\tname\n")
        n = 0
        for s in sorted(sf.syms, key=lambda x: x.addr):
            if s.addr <= TEXT_HI or s.name in fnames:
                continue
            d = dtype.get(s.name)
            if d is not None:
                ty, st = declare(d, "", tagmap).strip(), P.CLASS_NAME.get(d.cls, "?")
            else:
                ty, st = "?", "?"
            f.write(f"{s.addr:08x}\t{st}\t{ty}\t{s.name}\n")
            n += 1
    print(f"wrote psxsym-data.tsv ({n} data symbols)")

    # ---- globals we can actually use: PSX.SYM's type, our retail address
    repo = {}
    symfile = f"{REPO}/config/symbols.main.exe.txt"
    if os.path.exists(symfile):
        for line in open(symfile):
            m = re.match(r"\s*([A-Za-z_]\w*)\s*=\s*(0x[0-9A-Fa-f]+)\s*;", line)
            if m:
                repo[m.group(1)] = int(m.group(2), 16)
    statfile = {d.name: d.file.split("\\")[-1] for d in sf.defs
                if d.cls in (P.C_STAT, P.C_USTATIC)}
    n = 0
    with open(f"{args.out}/psxsym-globals.h", "w") as f:
        f.write("/* Generated by tools/symdump.py.\n"
                " * Globals PSX.SYM types AND our decomp already names, with the RETAIL\n"
                " * address.  Layouts come from the earlier build -- verify against\n"
                " * tools/access.py before relying on a field offset.\n */\n\n")
        emitted = set()
        for s2 in sorted(sf.syms, key=lambda x: x.addr):
            if (s2.addr <= TEXT_HI or s2.name in fnames or s2.name not in repo
                    or s2.name in emitted):
                continue
            d = dtype.get(s2.name)
            if d is None:
                continue
            where = statfile.get(s2.name)
            note = f"  /* 0x{repo[s2.name]:08x}" + (f", static in {where}" if where else "") + " */"
            f.write(f"extern {declare(d, s2.name, tagmap)};{note}\n")
            emitted.add(s2.name)
            n += 1
    print(f"wrote psxsym-globals.h ({n} typed globals our decomp names)")

    # ---- statics: what the original build hid inside a TU
    with open(f"{args.out}/psxsym-statics.tsv", "w") as f:
        f.write("#file\tkind\tname\n")
        n = 0
        for d in sf.defs:
            if d.cls not in (P.C_STAT, P.C_USTATIC):
                continue
            kind = "function" if ((d.type >> 4) & 3) == P.DT_FCN else "object"
            f.write(f"{d.file.split(chr(92))[-1]}\t{kind}\t{d.name}\n")
            n += 1
    print(f"wrote psxsym-statics.tsv ({n} static declarations)")


if __name__ == "__main__":
    main()
