#!/usr/bin/env python3
"""Dump everything PSX.SYM knows into reviewable reference artefacts.

PSX.SYM's addresses belong to a lost build, but its *names and types* are the
original source's.  None of that needs address correlation -- it keys by name.
Writes, under reference/:

  psxsym-types.h    structs/unions/enums/typedefs with the original field names
  psxsym-protos.h   function prototypes with the original parameter names
  psxsym-tu-map.tsv function -> source file, line, frame size, saved-reg mask
  psxsym-data.tsv   data symbols (globals) with their original types
  psxsym-statics.tsv symbols the original build declared `static`

These are *reference* material, not build inputs: types.h in particular uses the
demo build's layouts, which retail may have changed.  Check a field offset
against the disassembly before trusting it.
"""
from __future__ import annotations

import argparse, collections, os, re, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import psxsym as P

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FAKE = re.compile(r"^\.\d+fake$")


def stem(path: str) -> str:
    return path.split("\\")[-1].replace(".C", "").replace(".", "_")


def ident(tag: str, file: str, tagmap: dict[tuple[str, str], str]) -> str:
    """Resolve a struct tag to a C identifier.

    ``.NNNfake`` tags are the linker's names for anonymous aggregates and are
    numbered PER TRANSLATION UNIT -- `.57fake` in AUDIO.C and in 3DCTRL.C are
    unrelated types.  So they resolve through (file, tag); a real tag is global.
    """
    if not tag:
        return ""
    if FAKE.match(tag):
        hit = tagmap.get((file, tag))
        return hit if hit else f"{stem(file)}_{tag.replace('.', '_')}"
    return tag


def declare(d: P.Def, name: str, tagmap: dict[tuple[str, str], str]) -> str:
    """Full C declarator for `name` of `d`'s type.

    COFF stores up to six 2-bit derivations starting at bit 4, ordered from the
    identifier outwards: `short (*think[4])()` is ARY, then PTR, then FCN.  A
    pointer binds looser than `[]`/`()`, so it needs parentheses whenever a
    suffix is applied after it.
    """
    t = d.type
    base = P.BASE_TYPE.get(t & 0xF, f"?{t & 0xF}")
    if (t & 0xF) in (8, 9, 10):
        kw = {8: "struct", 9: "union", 10: "enum"}[t & 0xF]
        nm = ident(d.tag, d.file, tagmap)
        base = f"{kw} {nm}" if nm else kw
    dims = list(d.dims)
    decl = name
    for i in range(6):
        x = (t >> (4 + 2 * i)) & 3
        if x == P.DT_NON:
            continue
        if x == P.DT_PTR:
            decl = "*" + decl
        elif x == P.DT_ARY:
            if decl.startswith("*"):
                decl = f"({decl})"
            decl += f"[{dims.pop(0) if dims else 0}]"
        elif x == P.DT_FCN:
            if decl.startswith("*"):
                decl = f"({decl})"
            decl += "()"
    return f"{base} {decl}".rstrip()


def rettype_of(d: P.Def, tagmap: dict[tuple[str, str], str]) -> str:
    """Return type of a function symbol: its declarator minus the trailing ()."""
    return declare(d, "", tagmap).replace("()", "").strip()


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("sym", nargs="?", default=f"{REPO}/disks/demo/PSX.SYM")
    ap.add_argument("-o", "--out", default=f"{REPO}/reference")
    args = ap.parse_args()
    sf = P.load(args.sym)
    os.makedirs(args.out, exist_ok=True)

    # ---- anonymous tags (.133fake) get the name of the typedef that wraps them
    tagmap: dict[tuple[str, str], str] = {}
    for d in sf.defs:
        if d.cls == P.C_TPDEF and d.tag and FAKE.match(d.tag):
            tagmap.setdefault((d.file, d.tag), d.name)

    # ---- collect one definition per aggregate (they repeat once per TU)
    aggr: dict[str, tuple[str, int, list[P.Def]]] = {}
    cur = None
    for d in sf.defs:
        if d.cls in (P.C_STRTAG, P.C_UNTAG, P.C_ENTAG):
            kind = {P.C_STRTAG: "struct", P.C_UNTAG: "union", P.C_ENTAG: "enum"}[d.cls]
            cur = (kind, ident(d.name, d.file, tagmap), d.size, [])
        elif d.cls == P.C_EOS:
            if cur and cur[3]:
                nm = cur[1]
                if nm not in aggr or len(aggr[nm][2]) < len(cur[3]):
                    aggr[nm] = (cur[0], cur[2], cur[3])
            cur = None
        elif cur and d.cls in (P.C_MOS, P.C_MOU, P.C_MOE, P.C_FIELD):
            cur[3].append(d)

    with open(f"{args.out}/psxsym-types.h", "w") as f:
        f.write("/* Generated by tools/symdump.py from the demo's PSX.SYM.\n"
                " * Original field names and layouts, from an EARLIER BUILD than retail.\n"
                " * Reference only -- verify offsets against the disassembly.\n */\n\n")
        for nm in sorted(aggr):
            kind, size, members = aggr[nm]
            f.write(f"{kind} {nm} {{  /* size {size} */\n")
            for m in members:
                if kind == "enum":
                    f.write(f"    {m.name} = {m.offset},\n")
                    continue
                if m.cls == P.C_FIELD:
                    f.write(f"    {declare(m, m.name, tagmap)} : {m.size};"
                            f"  /* bit +{m.offset} */\n")
                else:
                    f.write(f"    {declare(m, m.name, tagmap)};  /* +0x{m.offset:x} */\n")
            f.write("};\n\n")
        seen = set()
        for d in sf.defs:
            if d.cls != P.C_TPDEF or d.name in seen:
                continue
            seen.add(d.name)
            if FAKE.match(d.tag or "") and tagmap.get((d.file, d.tag)) == d.name:
                kw = {8: "struct", 9: "union", 10: "enum"}.get(d.type & 0xF, "")
                f.write(f"typedef {kw} {d.name} {d.name};\n")
                continue
            f.write(f"typedef {declare(d, d.name, tagmap)};\n")
    print(f"wrote psxsym-types.h  ({len(aggr)} aggregates, {len(seen)} typedefs)")

    # ---- prototypes
    rettype = {d.name: d for d in sf.defs if d.cls in (P.C_EXT, P.C_STAT)}
    with open(f"{args.out}/psxsym-protos.h", "w") as f:
        f.write("/* Generated by tools/symdump.py -- original prototypes from PSX.SYM. */\n\n")
        for fn in sorted(sf.funcs, key=lambda x: (x.file, x.line)):
            r = rettype.get(fn.name)
            pre = rettype_of(r, tagmap) if r is not None else "int"
            params = ", ".join(declare(a, a.name, tagmap) for a in fn.args) or "void"
            static = "static " if r is not None and r.cls == P.C_STAT else ""
            f.write(f"{static}{pre} {fn.name}({params});"
                    f"  /* {fn.file.split(chr(92))[-1]}:{fn.line} */\n")
    print(f"wrote psxsym-protos.h ({len(sf.funcs)} prototypes, "
          f"{sum(1 for f in sf.funcs if f.args)} with named args)")

    # ---- TU map
    with open(f"{args.out}/psxsym-tu-map.tsv", "w") as f:
        f.write("#demo_addr\tsize\tfile\tline\tfsize\tmask\tstatic\tname\n")
        order = sorted(sf.funcs, key=lambda x: x.addr)
        for i, fn in enumerate(order):
            nxt = order[i + 1].addr if i + 1 < len(order) else fn.end_addr + 8
            r = rettype.get(fn.name)
            st = "static" if r is not None and r.cls == P.C_STAT else "extern"
            f.write(f"{fn.addr:08x}\t{nxt-fn.addr}\t{fn.file.split(chr(92))[-1]}\t{fn.line}\t"
                    f"{fn.fsize}\t{fn.mask & 0xFFFFFFFF:#010x}\t{st}\t{fn.name}\n")
    tus = len({f.file for f in sf.funcs})
    print(f"wrote psxsym-tu-map.tsv ({len(sf.funcs)} functions across {tus} source files)")

    # ---- data symbols (plain symbols outside .text) + their types where known
    TEXT_HI = 0x8008B02B
    dtype = {d.name: d for d in sf.defs if d.cls in (P.C_EXT, P.C_STAT, P.C_USTATIC)}
    fnames = {f.name for f in sf.funcs}
    with open(f"{args.out}/psxsym-data.tsv", "w") as f:
        f.write("#demo_addr\tstorage\ttype\tname\n")
        n = 0
        for s in sorted(sf.syms, key=lambda x: x.addr):
            if s.addr <= TEXT_HI or s.name in fnames:
                continue
            d = dtype.get(s.name)
            if d is not None:
                ty, st = declare(d, "", tagmap).strip(), P.CLASS_NAME.get(d.cls, "?")
            else:
                ty, st = "?", "?"
            f.write(f"{s.addr:08x}\t{st}\t{ty}\t{s.name}\n")
            n += 1
    print(f"wrote psxsym-data.tsv ({n} data symbols)")

    # ---- statics: what the original build hid inside a TU
    with open(f"{args.out}/psxsym-statics.tsv", "w") as f:
        f.write("#file\tkind\tname\n")
        n = 0
        for d in sf.defs:
            if d.cls not in (P.C_STAT, P.C_USTATIC):
                continue
            kind = "function" if ((d.type >> 4) & 3) == P.DT_FCN else "object"
            f.write(f"{d.file.split(chr(92))[-1]}\t{kind}\t{d.name}\n")
            n += 1
    print(f"wrote psxsym-statics.tsv ({n} static declarations)")


if __name__ == "__main__":
    main()
