#include "common.h"
#include "main.exe.h"
#include "gte.h"

/*
 * drawF3 (0x8005d0d4, 0x128 bytes) — the flat-triangle (POLY_F3) primitive
 * renderer of the DrawTMD handler family, and the anchor for the restricted
 * gte.h inline-asm policy (docs/gte-policy.md).  The carved .s marks it a
 * "Handwritten function", and the calling convention below independently
 * supports that classification.
 *
 * STATUS: NON_MATCHING — 5 of 296 byte values differ (72 of 74 instructions
 * exact).  An earlier reconstruction incorrectly called the opening
 * `beq $v1,$v0` unreachable from C.  Computing the sentinel difference in the
 * already-pinned $v1 carrier lets combine turn the zero test back into exactly
 * that branch, with no subtraction left in the output.
 *
 * The remaining two words are a coupled consequence of the reset at 0x8005d150:
 * the target has `addiu $s0,$zero,0` and tests the masked flag against $zero;
 * cc1's integer-zero movsi is `addu $s0,$zero,$zero` (`move`), and retaining
 * $s0 as the RHS of the comparison is the pure-C dependency that keeps that
 * reset between `cfc2` and `and` while preserving the target's branch-delay
 * `nop`.  Comparing against literal zero instead lets reorg sink the reset into
 * the delay slot and makes the function one instruction short.
 *
 * As a diagnostic, replacing the RHS assignment with one volatile inline
 * `li %0,0` immediately after gte_stflg and testing literal zero produces an
 * exact 0-byte diff.  It is deliberately not retained: `li` is not a GTE
 * operation and hiding it in gte.h would only disguise assembly as C.  A scan
 * of cc1-produced assembly found no C zero assignment spelled `li`; all 17
 * target `addiu r,$zero,0` occurrences are confined to DrawTMD and its 16
 * draw handlers.
 *
 * Everything else is exact, including all COP2 data moves, the three GTE
 * commands, the deferred ordering-table insertion, and every guard delay slot.
 * The default build keeps the byte-identical INCLUDE_ASM stub; the #else draft
 * is the reference reconstruction (build with `NON_MATCHING=drawF3 ./Build`).
 *
 * Re-verified 2026-07-17 against a task brief that (incorrectly) described this
 * as a fresh, never-attacked park: it is neither fresh nor a real outstanding
 * target (config/handwritten-asm.txt, triage.py's parked() and docs/gte-policy.md
 * already close this class; findsimilar.py --targets ranks it 0.008 similarity,
 * dead last of ~1010 candidates — the brief was generated by scanning
 * NON_MATCHING files by raw residual byte count, not by triage.py's exclusion
 * list). Two things were re-tested directly rather than taken on faith:
 *   - RTL (tools/rtldump.py --pass cse): the reset (insn 106, hard reg 16,
 *     `(set (reg:SI 16) (const_int 0))` with a REG_EQUAL note) and the branch
 *     (insn 108) are ADJACENT in the same cse block (102..187) — no CODE_LABEL
 *     between them. So the register-vs-literal residual is not a cse
 *     block-boundary artifact (a plausible-sounding alternative hypothesis);
 *     cc1 simply does not fold a hard, multi-use register's known-constant
 *     value into a later comparison.
 *   - Splitting the fused `(code = 0)` back into two statements (`code = 0;`
 *     then `if ((flag & mask) == 0)`) was rebuilt and measured, not just
 *     reasoned about: it produces `bnez` as expected, but reorg immediately
 *     sinks the now-independent reset into the branch's delay slot, and the
 *     function drops to 292/296 bytes (LENGTH MISMATCH) — reproducing exactly
 *     the failure this comment already described.
 * tools/autorules.py --guided (rtlguide-informed, 135 compiled candidates)
 * found no improving path either. Nothing here changed; do not re-attempt
 * without a genuinely new angle, and do not let a byte-count scan alone
 * resurface this function as a target again.
 *
 * Non-ABI entry — the DrawTMD dispatcher hands the handler its working state in
 * live registers (no stack frame, no callee-save):
 *   $v0 ($2)  batch primitive count (0x304 sentinel => 1)
 *   $t0 ($8)  deferred ordering-table slot from the previous primitive
 *   $t2 ($10) ordering-table base
 *   $t3 ($11) output packet cursor (POLY_F3, 0x14 bytes each)
 *   $t4 ($12) transformed-vertex (SVECTOR) base
 *   $t5 ($13) input primitive cursor (0x10 bytes each)
 *   $t6 ($14) running item budget, decremented by this batch's count
 *   $t9 ($25) ordering-table length (depth clamp)
 *   $s0 ($16) pending-primitive code byte carried across iterations (0 = none)
 */

#ifndef NON_MATCHING
INCLUDE_ASM("config/../.shake/gen/main.exe/asm/nonmatchings/drawF3", drawF3);
#else

typedef struct
{
    u8     mode[4]; /* +0x0 */
    u_long rgb;     /* +0x4 (r,g,b,code) */
    u16    v0;      /* +0x8 vertex index 0 */
    u16    v1;      /* +0xA vertex index 1 */
    u16    v2;      /* +0xC vertex index 2 */
    u16    norm;    /* +0xE */
} F3Prim;

/* $s0 is the only callee-saved register the handler clobbers.  A file-scope
 * global register variable reserves it WITHOUT a prologue save/restore — the
 * DrawTMD dispatcher owns the save, exactly the non-ABI handler contract.
 * $t6 (budget) and $t3 (packet) are handed back to the dispatcher updated, so
 * their final writes must not be dead-eliminated / sunk into the return delay
 * slot: global register variables keep the stores in place. */
register int code   __asm__("$16");
register int budget __asm__("$14");
register u_long *packet __asm__("$11");

void drawF3(void)
{
    register int     r_v0    __asm__("$2");
    register u_long *ot_in   __asm__("$8");
    register int     ot_base __asm__("$10");
    register int     vbase   __asm__("$12");
    register F3Prim *prim    __asm__("$13");
    register int     ot_max  __asm__("$25");

    register SVECTOR *r0 __asm__("$4");
    register SVECTOR *r1 __asm__("$5");
    register SVECTOR *r2 __asm__("$6");
    register int      n    __asm__("$15");
    register int      half __asm__("$9");
    register int      mask __asm__("$3");
    u_long *ot_slot;
    int flag;
    int mac0;

    ot_slot = ot_in;
    /* The temporary subtraction survives long enough to preserve operand
     * order, then combine reduces this back to the target equality branch. */
    mask = 0x304u - (u32)r_v0;
    n = 1;
    if (mask != 0)
    {
        n = r_v0;
    }
    budget = budget - n;
loop:
    {
        r0 = (SVECTOR *)(prim->v0 * 8);
        r1 = (SVECTOR *)(prim->v1 * 8);
        r2 = (SVECTOR *)(prim->v2 * 8);
        r0 = (SVECTOR *)((int)r0 + vbase);
        r1 = (SVECTOR *)((int)r1 + vbase);
        r2 = (SVECTOR *)((int)r2 + vbase);
        gte_ldv3(r0, r1, r2);
        mask = 0x1C66000;
        gte_rtpt_raw();
        if (code != 0)
        {
            *ot_slot = (u_long)packet;
            *((u8 *)ot_slot + 3) = 0;
            gte_strgb(packet[1]);
            *((u8 *)packet + 7) = (u8)code;
            packet += 5;
        }
        gte_stflg(flag);
        /* This assignment expression keeps the reset after cfc2 and before
         * the flag test; see the coupled two-word residual above. */
        if ((flag & mask) == (code = 0))
        {
            gte_nclip_raw();
            gte_stsz3r(r0, r1, r2);
            ot_slot = (u_long *)((int)r0 + (int)r1);
            ot_slot = (u_long *)((int)ot_slot + (int)r2);
            half = (u_long)ot_slot >> 2;
            ot_slot = (u_long *)((u_long)ot_slot >> 4);
            gte_stmac0(mac0);
            ot_slot = (u_long *)((u_long)ot_slot + half);
            ot_slot = (u_long *)((u_long)ot_slot >> 4);
            if (mac0 > 0)
            {
                half = (int)ot_slot - ot_max;
                if ((int)ot_slot > 0)
                {
                    ot_slot = (u_long *)((int)ot_slot * 4);
                    if (half < 0)
                    {
                        gte_ldrgb(prim->rgb);
                        ot_slot = (u_long *)((int)ot_slot + ot_base);
                        mac0 = *ot_slot;
                        gte_dpcs_raw();
                        *packet = mac0;
                        mask = 4;
                        *((u8 *)packet + 3) = mask;
                        gte_stsxy3_f3(packet);
                        code = 0x20;
                    }
                }
            }
        }
        n = n - 1;
        prim += 1;
    }
    if (n > 0)
    {
        goto loop;
    }
    if (code != 0)
    {
        *ot_slot = (u_long)packet;
        *((u8 *)ot_slot + 3) = 0;
        gte_strgb(packet[1]);
        *((u8 *)packet + 7) = (u8)code;
        packet += 5;
    }
}

#endif
