#include "common.h"
#include "main.exe.h"
#include "effect.h"

/* BEGIN PSX.SYM — the original source's own facts, from the demo disc's
 * debug symbols. Regenerate with `tools/symnote.py --write`; see
 * docs/psx-sym.md. Do not hand-edit.
 *
 * static void DrawExplosion(struct tag_EffectSlot *ef);
 *     EFFECT.C:1177, 57 src lines, frame 32 bytes, saved-reg mask 0x80010000
 *
 * Original parameters and locals (the demo build's register allocation may
 * differ from retail, but the COUNT and TYPES drive cc1's codegen and carry
 * over). A repeated name is a nested-block scope, not a duplicate:
 *     param $a1       struct tag_EffectSlot * ef
 *     reg   $a2       struct ExplosionType * param
 *     reg   $s0       struct Sprite3D * spr
 *     reg   $a3       unsigned char alfa
 *
 * Globals it touches, as the original declared them:
 *     extern struct Sprite3D *sprBomb[3];
 * END PSX.SYM */

/*
 * Matching notes (all verified against the original bytes):
 *  - `ef->param` here is `ExplosionType` (see DrawHinoko.c, an almost
 *    identical sibling in this same family), NOT `BloodType`/`smoke` as
 *    Ghidra's own field names suggest — the numeric offsets it derived
 *    are right (vec@0x0, pos@0x8, rotate@0x18, scale@0x1c, time@0x20,
 *    mode@0x21) but its names (blood.py/pz/scale, smoke.*) are its own
 *    wrong union-member guess for those same offsets.
 *  - Declared plain (not `static`, though PSX.SYM's original prototype was)
 *    so SetExplosion.c's `extern void DrawExplosion(...)` can take its
 *    address across our per-function split files; `static` only affects
 *    linkage/visibility, not the body's generated bytes, since this
 *    function is only ever reached indirectly through `ef->proc`.
 *  - Ghidra's `unaff_s0` — its marker for "could not trace this register's
 *    source" — happens to still be RIGHT here (sprBomb[1] for both the
 *    mode==1 and mode==2 arms, sprBomb[0] for mode==0). The raw address our
 *    disassembly printed for that shared tail (labelled `D_800BEB6C`) is
 *    simply `&sprBomb[1]` (sprBomb sits at 0x800beb68, a 3-pointer array,
 *    and our tooling doesn't fold `base+4` back into `sprBomb[1]`) — write
 *    `sprBomb[1]` directly, don't add a new symbol.
 *  - `param->mode` (values 0/1/2) is a real `switch`, not an if/else-if
 *    chain: cc1's expand_case picks the SORTED middle value (1) as the
 *    first pivot test, then splits the rest with `slti ...,2` (catching 0
 *    on the low side, 2 on the high side), then re-tests each explicitly —
 *    exactly Ghidra's nested `if (mode==1) {} else { if (mode<2) { if
 *    (mode==0) {} } else if (mode==2) {} }` shape, which is cc1's balanced
 *    compare tree for a 3-value switch, not literal source nesting.
 *    **Case-body memory order is 0, 1, 2 even though the TEST order is
 *    1, then {0,2}** — the source must list `case 0:` first (cookbook's
 *    "case-body memory order reveals source case order" rule, generalized
 *    to a 3-way switch): writing `case 1:` first put case 1's compiled body
 *    where case 0's belongs.
 *  - case 0 is a real if/else (mutually exclusive: re-init OR smoke
 *    update, never both); case 1's smoke update runs UNCONDITIONALLY after
 *    its own re-init `if` (no `else` — Ghidra already renders this
 *    correctly for case 1, only case 0 needed the same shape confirmed).
 *  - **case 1 and case 2 both end with `spr = sprBomb[1]; break;` as their
 *    LAST statement** (case 2's assignment must come AFTER its
 *    `if (param->time == 0) {...}`, not before) — only with the identical
 *    statement as each case's true tail does cc1 merge the two into ONE
 *    physical `lw sprBomb[1]` block reached by both (a real cross-jump on
 *    genuinely-identical tails, not a coincidence of source order).
 *  - case 2's alpha fade mirrors DrawHinoko's `(t * 0x80) / 30` idiom
 *    (different divisor: `(param->time << 7) / 5`) — but unlike DrawHinoko,
 *    do NOT cache `param->time` in a shared local first: two DIRECT reads
 *    (once inline in the shift/divide expression, once in the zero-check)
 *    reproduce the target's two separate `lbu`s, because here `time`'s
 *    register gets EVICTED by the intervening `scale`/`rotate` load/store
 *    pair (both fit in the same one temp register target uses) forcing a
 *    genuine reload — caching in a named local instead gave the value its
 *    OWN register that survives untouched, so cc1 (correctly) reused it
 *    instead of reloading, one instruction short. Put the alfa statement
 *    FIRST in the case (before scale/rotate), matching the read order.
 *  - The tail integrates `vec.vx/vy/vz` into `pos.vx/vy/vz`: write the
 *    `.vx` addition before `.vy` — the reverse order swaps which of
 *    a0/a1 each ends up in.
 */
typedef struct
{
    GsCOORDINATE2 locate; /* +0x00 */
    SVECTOR rotate;       /* +0x50 */
    s16 id;               /* +0x58 */
    s16 attribute;        /* +0x5a */
    SVECTOR clip;         /* +0x5c */
    long scale;           /* +0x64 */
    GsSPRITE sprite;      /* +0x68 */
} Sprite3D;

extern Sprite3D *sprBomb[3];
extern void UpdateCoordinate(Sprite3D *m);
extern void DrawSprite(Sprite3D *s);

void DrawExplosion(TEffectSlot *ef)
{
    ExplosionType *param;
    Sprite3D *spr;
    u8 alfa;
    long rotate;

    param = &ef->param.explosion;
    alfa = 0x80;
    switch (param->mode)
    {
    case 0:
        if (param->time == 0)
        {
            param->time = 3;
            param->mode = param->mode + 1;
        }
        else
        {
            param->scale = param->scale + 0x2000;
            param->rotate = param->rotate + 0x64000;
        }
        spr = sprBomb[0];
        break;
    case 1:
        if (param->time == 0)
        {
            param->time = 5;
            param->mode = param->mode + 1;
        }
        param->scale = param->scale + 0x2000;
        param->rotate = param->rotate + 0x64000;
        spr = sprBomb[1];
        break;
    case 2:
        alfa = (u8)((param->time << 7) / 5);
        param->scale = param->scale - 0x333;
        param->rotate = param->rotate + 0x5a000;
        if (param->time == 0)
        {
            ef->proc = 0;
        }
        spr = sprBomb[1];
        break;
    }
    param->time = param->time - 1;
    param->pos.vx = param->pos.vx + param->vec.vx;
    param->pos.vy = param->pos.vy + param->vec.vy;
    param->pos.vz = param->pos.vz + param->vec.vz;
    spr->locate.coord.t[0] = param->pos.vx;
    spr->locate.coord.t[1] = param->pos.vy;
    spr->locate.coord.t[2] = param->pos.vz;
    spr->scale = param->scale;
    rotate = param->rotate;
    spr->sprite.r = alfa;
    spr->sprite.g = alfa;
    spr->sprite.b = alfa;
    spr->sprite.rotate = rotate;
    UpdateCoordinate(spr);
    DrawSprite(spr);
}
